FROM ghcr.io/fixposition/fixposition-sdk:noetic-dev

# RUN <<EOF
#     # Install additional packages
#     set -e
#     export DEBIAN_FRONTEND=noninteractive
#     apt-get -y update
#     apt-get -y --with-new-pkgs upgrade
#     apt-get -y --no-install-recommends install some-package another-package ...
#     apt-get -y autoremove
#     apt-get clean
# EOF
