####################################################################################################
#
#    Copyright (c) 2023
#    Fixposition AG
#
####################################################################################################
#
# Fixposition WheelSensor Message
#
#
####################################################################################################

# Velocity values in [mm/s] as integer 32bit
# Options:
# Option 1: One value, will be input in the x axis
# Option 2: Two values, will be input in the x and y axis
# Option 2: Three values, will be input in the x, y, and z axis
int32[] speeds
