####################################################################################################
#
#    Copyright (c) 2023
#    Fixposition AG
#
####################################################################################################
#
# Fixposition Covariance Warning Message
#
#
####################################################################################################

std_msgs/Header header
geometry_msgs/Vector3 jump         # Position change
geometry_msgs/Vector3 covariance   # Covariance
